'''9/28/21 by Wyatt Homola

This program addresses a student complaint that function composition, and I quote, "sucks."  It demonstrates the bifurcation diagram as 
generated by the iteration of a quadratic function x1 = x0 ** 2 + c for different values of c. 
'''

import matplotlib.pyplot as plt
import numpy as np

def getiterations(c, initial, count): 

    '''Get count iterations of the recursive formula x1 = x0 ** 2 + c with starting x value of initial
    
        1) Start at the coordinates (initial, 0).  
        2) On the first iteration, reach point (initial, f(initial))
        3) For demonstration purpose, travel over to the line y = x to show that the output value becomes the next input value: reach point (f(initial), f(initial))
        4) Reach the next iteration, (f(x), f(f(x)), repeating step 2, then repeat step 3.
        
        So after count iterations, there are count coordinates in the list which lie on the parabola, count coordinates on the line y = x, and a single 
        initial coordinate on the x axis.
        Thus, in total this function generates 2 * count + 1 coordinate pairs. 
    '''
   
    coordinates = np.array([[initial, 0]])
    for i in range(count): 
        # Numpy slicing syntax for "the y second value of the last coordinate pair"
        x_new = coordinates[-1:, 1][0]
        y_new = (x_new ** 2) + c
        # Append the new point which lies on the parabola
        coordinates = np.concatenate((coordinates, [[x_new, y_new]]), axis=0)
        # Append the new point which lies on y = x
        coordinates = np.concatenate((coordinates, [[y_new, y_new]]), axis=0)
        
    return coordinates

c = [-1.4015, -3 / 4, -1.3, -1.8]

# Get the x and y coordinates for the trajectories
coordinates = [getiterations(q, 0, 100) for q in c]
# Get x coordinates for the parabolas and lines
parabola_x = np.arange(-2, 2, 0.1)
parabola_y = [[i**2 + q for i in parabola_x] for q in c]
# parabola_x = [np.arange(-2, -2, 0.1), np.arange(-1.5, 0.7, 0.1), np.arange(-1, 0.2, 0.1), np.arange(-1.5, 1, 0.1)]
# parabola_y = []
# for count, item in enumerate(c): 
#     # parabola_y = [[i**2 + q for i in parabola_x] for q in c]
#     parabola_y.append([i**2 + count for i in parabola_x[count]])

nrows = 2
ncols = 2
fig, ax = plt.subplots(nrows, ncols)
count = 0 
for i in range(nrows): 
    for j in range(ncols): 
        ax[i, j].plot(coordinates[count][:, 0], coordinates[count][:, 1], label="iterations")
        ax[i, j].plot(parabola_x, parabola_y[count], label="parabola")
        ax[i, j].plot(parabola_x, parabola_x, label="line")
        count += 1
# ax.plot(np.arange(-1, 1, 0.1), np.square(np.arange(-1, 1, 0.1)), label="parabola")
plt.show()